/**
 * XRPL Escrow Service
 * Builds and tracks EscrowCreate / EscrowFinish / EscrowCancel transactions
 * used to lock XRP during P2P trades on the XRPL testnet.
 *
 * The service operates in "prepare & record" mode: it produces ready-to-sign
 * transaction JSON and generates a random crypto-condition preimage per escrow.
 * Signing and submission happen client-side (the server never holds seeds);
 * the resulting transaction hash is reported back via /api/p2p/submit-escrow-hash.
 */

const crypto = require('node:crypto');

// XRP has 6 decimal places: 1 XRP = 1,000,000 drops
const DROPS_PER_XRP = 1000000;

// Classic XRPL addresses start with 'r' and are 25-35 base58 characters
const CLASSIC_ADDRESS_REGEX = /^r[1-9A-HJ-NP-Za-km-z]{24,34}$/;

function xrpToDrops(amount) {
  const value = Number(amount);
  if (!Number.isFinite(value)) {
    throw new Error('Invalid XRP amount');
  }
  return Math.round(value * DROPS_PER_XRP).toString();
}

function isValidClassicAddress(address) {
  return typeof address === 'string' && CLASSIC_ADDRESS_REGEX.test(address);
}

// Seconds between the Unix epoch and the Ripple epoch (2000-01-01T00:00:00Z)
const RIPPLE_EPOCH_OFFSET = 946684800;

// Escrow lifecycle statuses stored on p2p_orders.escrow_status
const ESCROW_STATUS = {
  NONE: 'none',
  PREPARED: 'prepared',   // EscrowCreate JSON issued, awaiting on-chain submission
  LOCKED: 'locked',       // EscrowCreate confirmed on ledger, XRP locked
  FINISH_PENDING: 'finish_pending', // EscrowFinish JSON issued, awaiting on-chain submission + hash confirmation
  REFUND_PENDING: 'refund_pending', // EscrowCancel JSON issued, awaiting on-chain submission + hash confirmation
  CANCEL_PENDING: 'cancel_pending', // Expiry sweep: escrow still on-chain, awaiting on-chain cancellation
  FINISHED: 'finished',   // EscrowFinish confirmed on ledger, XRP released to buyer
  CANCELLED: 'cancelled', // EscrowCancel confirmed on ledger after expiry, XRP returned to seller
  REFUNDED: 'refunded'    // EscrowCancel confirmed on ledger after dispute/cancel of the trade
};

// Trade deadline defaults (PRD: finish within 2h, auto-cancel after 24h)
const FINISH_AFTER_SECONDS = parseInt(process.env.ESCROW_FINISH_AFTER_SECONDS, 10) || 2 * 60 * 60;
const CANCEL_AFTER_SECONDS = parseInt(process.env.ESCROW_CANCEL_AFTER_SECONDS, 10) || 24 * 60 * 60;

const HASH_REGEX = /^[A-Fa-f0-9]{64}$/;

function toRippleTime(date) {
  return Math.floor(date.getTime() / 1000) - RIPPLE_EPOCH_OFFSET;
}

/**
 * Generate a random 32-byte fulfillment preimage for one escrow.
 * A fresh preimage MUST be generated per escrow; the on-chain condition is
 * SHA-256 of the preimage bytes. The preimage is stored server-side and is
 * revealed only inside the EscrowFinish flow after payment verification.
 *
 * @returns {string} 64-character uppercase hex preimage (the fulfillment)
 */
function generatePreimage() {
  return crypto.randomBytes(32).toString('hex').toUpperCase();
}

/**
 * PREIMAGE-SHA-256 crypto-condition, as required on-chain:
 *   A0258020 <SHA-256 of the preimage bytes> 8101 <cost>
 * where <cost> is the preimage length in bytes (1 byte). A bare SHA-256
 * digest is REJECTED by rippled with temMALFORMED (verified on testnet).
 *
 * @param {string} preimageHex — 64-character hex fulfillment preimage
 * @returns {string} 78-character uppercase hex condition
 */
function conditionFromPreimage(preimageHex) {
  if (!preimageHex || !HASH_REGEX.test(preimageHex)) {
    throw domainError('Invalid escrow preimage');
  }
  const digest = crypto.createHash('sha256')
    .update(Buffer.from(preimageHex, 'hex'))
    .digest('hex');
  const cost = (preimageHex.length / 2).toString(16).padStart(2, '0');
  return ('A0258020' + digest + '8101' + cost).toUpperCase();
}

/**
 * PREIMAGE-SHA-256 fulfillment blob for the EscrowFinish transaction:
 *   A0 <contentLen> 80 <preimageLen> <preimage bytes>
 * (SEQUENCE { [0] OCTET STRING }). For the 32-byte preimages generated by
 * this service this is always `A0228020 <preimage>`.
 *
 * @param {string} preimageHex — 64-character hex preimage
 * @returns {string} uppercase hex fulfillment
 */
function fulfillmentFromPreimage(preimageHex) {
  if (!preimageHex || !HASH_REGEX.test(preimageHex)) {
    throw domainError('Invalid escrow preimage');
  }
  const len = preimageHex.length / 2;
  const lenHex = len.toString(16).padStart(2, '0');
  return ('A0' + (len + 2).toString(16).padStart(2, '0') + '80' + lenHex + preimageHex).toUpperCase();
}

function domainError(message, statusCode = 400) {
  const err = new Error(message);
  err.statusCode = statusCode;
  return err;
}

function assertValidAddress(address, field) {
  if (!address || !isValidClassicAddress(address)) {
    throw domainError(`Invalid XRPL address: ${field}`);
  }
}

function assertValidAmount(xrpAmount) {
  const amount = Number(xrpAmount);
  if (!Number.isFinite(amount) || amount <= 0) {
    throw domainError('xrpAmount must be a positive number');
  }
  return amount;
}

function assertValidHash(txHash, field = 'txHash') {
  if (!txHash || !HASH_REGEX.test(txHash)) {
    throw domainError(`Invalid transaction hash: ${field}`);
  }
}

/**
 * Build an unsigned EscrowCreate transaction locking XRP for the buyer.
 */
function prepareEscrowCreate({
  sourceAddress,
  destinationAddress,
  xrpAmount,
  orderId,
  finishAfterSeconds = FINISH_AFTER_SECONDS,
  cancelAfterSeconds = CANCEL_AFTER_SECONDS
}) {
  assertValidAddress(sourceAddress, 'sourceAddress');
  assertValidAddress(destinationAddress, 'destinationAddress');
  const amount = assertValidAmount(xrpAmount);
  if (!orderId || typeof orderId !== 'string') {
    throw domainError('orderId is required');
  }

  const now = Date.now();
  const finishAfter = toRippleTime(new Date(now + finishAfterSeconds * 1000));
  const cancelAfter = toRippleTime(new Date(now + cancelAfterSeconds * 1000));
  // Random per-escrow preimage; the caller stores the encoded fulfillment
  // server-side and reveals it only inside the EscrowFinish flow.
  const preimage = generatePreimage();
  const fulfillment = fulfillmentFromPreimage(preimage);
  const condition = conditionFromPreimage(preimage);

  const transaction = {
    TransactionType: 'EscrowCreate',
    Account: sourceAddress,
    Destination: destinationAddress,
    Amount: xrpToDrops(amount.toString()),
    Condition: condition,
    FinishAfter: finishAfter,
    CancelAfter: cancelAfter,
    Memos: [
      {
        Memo: {
          MemoData: Buffer.from(`cryptopay:${orderId}`, 'utf8').toString('hex').toUpperCase()
        }
      }
    ]
  };

  return { transaction, condition, fulfillment, finishAfter, cancelAfter };
}

/**
 * Build an unsigned EscrowFinish transaction releasing locked XRP to the buyer.
 */
function prepareEscrowFinish({ account, owner, offerSequence, condition, fulfillment }) {
  assertValidAddress(account, 'account');
  assertValidAddress(owner, 'owner');
  // Conditions are 78-char PREIMAGE-SHA-256 crypto-conditions (A0258020…8101xx)
  if (!condition || !/^[A-Fa-f0-9]{78}$/.test(condition)) {
    throw domainError('Invalid escrow condition');
  }
  if (!fulfillment || !/^[A-Fa-f0-9]+$/.test(fulfillment)) {
    throw domainError('Invalid escrow fulfillment');
  }

  const transaction = {
    TransactionType: 'EscrowFinish',
    Account: account,
    Owner: owner,
    Condition: condition,
    Fulfillment: fulfillment.toUpperCase()
  };

  if (offerSequence !== undefined && offerSequence !== null) {
    const seq = Number(offerSequence);
    if (!Number.isInteger(seq) || seq < 0) {
      throw domainError('Invalid escrow offer sequence');
    }
    transaction.OfferSequence = seq;
  }

  return transaction;
}

/**
 * Build an unsigned EscrowCancel transaction returning expired escrow to the seller.
 */
function prepareEscrowCancel({ account, owner, offerSequence }) {
  assertValidAddress(account, 'account');
  assertValidAddress(owner, 'owner');

  const transaction = {
    TransactionType: 'EscrowCancel',
    Account: account,
    Owner: owner
  };

  if (offerSequence !== undefined && offerSequence !== null) {
    const seq = Number(offerSequence);
    if (!Number.isInteger(seq) || seq < 0) {
      throw domainError('Invalid escrow offer sequence');
    }
    transaction.OfferSequence = seq;
  }

  return transaction;
}

module.exports = {
  ESCROW_STATUS,
  FINISH_AFTER_SECONDS,
  CANCEL_AFTER_SECONDS,
  toRippleTime,
  generatePreimage,
  conditionFromPreimage,
  fulfillmentFromPreimage,
  prepareEscrowCreate,
  prepareEscrowFinish,
  prepareEscrowCancel,
  assertValidAddress,
  assertValidAmount,
  assertValidHash
};
